version: '1.0'

services:
  mysql-container:
    container_name: mysql-container
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'media'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mssql_data:/var/opt/mssql/data

  softcut-data:
    build: ./softcut-data
    ports:
      - "3001:3001"
    volumes:
      - ./softcut-data:/src/
      - nodemodules-data:/softcut-data/node_modules
    depends_on:
      - mysql-container

  softcut-ui:
    build: ./softcut-ui
    ports:
      - "4200:4200"
    volumes:
      - ./softcut-ui:/src/
      - nodemodules-ui:/src/node_modules
    depends_on:
      - softcut-data
      - mysql-container

volumes:
  nodemodules-ui: {}
  nodemodules-data: {}
